### ISSUE TITLE
Additional of Advanced Data Structures Like Trie and Segment Tree

### ISSUE THREAD

**Issue by monieshravichandrran** [Ayon-SSP/The-SDE-Prep#68]
Hey Hi. Would like to contribute to this repository by adding the explaination and code of Advanced Data Structures like Trie and Segment Tree

Can you raise this under hacktoberfest tag and assign it to me?

**Comment by Ayon-SSP** [comment]
**Go For it 🙂**

**Comment by monieshravichandrran** [comment]
Hey I have raised PR explaining the Data Structure and the implementation and a couple of most solved questions using the data strcuture

#73 PR
